### ISSUE TITLE
support param 'response_format' in IChatCompletionsBuilder

### ISSUE THREAD

**Issue by DenisYin66** [northes/go-moonshot#22]
Your issue may already be reported!
Please search on the [issue tracker](https://github.com/northes/go-moonshot/issues) before creating one.

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by northes** [comment]
Thank you for your issue, we have added this parameter!
