### ISSUE TITLE
Support for lower version of go

### ISSUE THREAD

**Issue by ClayCheung** [northes/go-moonshot#3]
是否考虑降低 go 版本，这样其他低版本的项目中也可以更容易的引用这个库。有许多场景是在原有的项目中增加 LLM 相关的功能。

就像 [go-openai](https://github.com/sashabaranov/go-openai/blob/master/go.mod) 就是基于 go1.18 的

**Comment by northes** [comment]
您好，感谢反馈，我会在下个版本中将所需使用的Go版本降到1.18
